# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Virtualisation
  product: Virtualisation
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:

    - title: Overview
      url: /p2_landing_page.html
      output: web

  - title: Vagrant
    output: web, pdf
    folderitems:

    - title: Vagrant Atlas
      url: /p2_vagrant.html
      output: web, pdf

    - title: Vagrant on Windows
      url: /p2_sample1.html
      output: web, pdf

    - title: Vagrant on Linux
      url: /p2_sample2.html
      output: web, pdf

  - title: Docker
    output: web, pdf
    folderitems:

    - title: Docker on Windows
      url: /p2_sample3.html
      output: web, pdf

    - title: Docker on Linux
      url: /p2_sample4.html
      output: web, pdf

# Copyright 2021 Google LLC
